// Generated by CoffeeScript 1.3.1
(function() {
  var fjs, _,
    __slice = [].slice;

  fjs = function(_) {
    var add, arrays, basics, call, chain, compose, curry, debug, div, each, eq, filter, find, first, flip, functions, get, groupBy, gt, gte, head, id, indexOf, invoke, last, log, lt, lte, map, max, memoize, method, min, mult, negate, objects, reduce, rest, reverse, set, sort, sortBy, sub, tail, take, us;
    curry = function(f) {
      var call;
      call = function() {
        var args, inner;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (args.length >= f.length) {
          return f.apply(null, args);
        } else {
          inner = function() {
            var args2, innerArgs;
            args2 = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            innerArgs = args.concat(args2);
            return call.apply(null, innerArgs);
          };
          inner.name = f.name;
          inner.toString = function() {
            return f.toString();
          };
          return inner;
        }
      };
      call.name = f.name;
      call.toString = function() {
        return f.toString();
      };
      return call;
    };
    flip = function(f) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return f.apply(null, args.reverse());
      };
    };
    id = function(a) {
      return a;
    };
    method = function(func) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return func.apply(null, [this].concat(__slice.call(args)));
      };
    };
    chain = function() {
      var funcs;
      funcs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return compose(funcs.reverse());
    };
    functions = {
      curry: curry,
      flip: flip,
      id: id,
      method: method,
      chain: chain
    };
    get = curry(function(name, obj) {
      return obj[name];
    });
    set = curry(function(name, value, obj) {
      obj[name] = value;
      return obj;
    });
    call = function() {
      var args, name;
      name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return function() {
        var innerArgs, obj;
        obj = arguments[0], innerArgs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        if (!(obj[name] != null) || !_.isFunction(obj[name])) {
          throw new Error("Object " + obj + " has no method " + name);
        }
        return obj[name].apply(obj, args.concat(innerArgs));
      };
    };
    objects = {
      get: get,
      set: set,
      call: call
    };
    log = function(arg) {
      console.log(arg);
      return arg;
    };
    debug = {
      log: log
    };
    eq = curry(function(a, b) {
      return b === a;
    });
    lt = curry(function(a, b) {
      return b < a;
    });
    lte = curry(function(a, b) {
      return b <= a;
    });
    gt = curry(function(a, b) {
      return b > a;
    });
    gte = curry(function(a, b) {
      return b >= a;
    });
    add = curry(function(a, b) {
      return b + a;
    });
    sub = curry(function(a, b) {
      return b - a;
    });
    mult = curry(function(a, b) {
      return b * a;
    });
    div = curry(function(a, b) {
      return b / a;
    });
    negate = function(a) {
      return !a;
    };
    basics = {
      eq: eq,
      lt: lt,
      lte: lte,
      gt: gt,
      gte: gte,
      add: add,
      sub: sub,
      mult: mult,
      div: div,
      negate: negate
    };
    memoize = _.memoize;
    compose = _.compose;
    find = curry(function(iterator, list) {
      return _.find(list, iterator);
    });
    map = curry(function(iterator, list) {
      return _.map(list, iterator);
    });
    filter = curry(function(iterator, list) {
      return _.filter(list, iterator);
    });
    each = curry(function(iterator, list) {
      return _.each(list, iterator);
    });
    min = curry(function(iterator, list) {
      return _.min(list, iterator);
    });
    max = curry(function(iterator, list) {
      return _.max(list, iterator);
    });
    sortBy = curry(function(iterator, list) {
      return _.sortBy(list, iterator);
    });
    groupBy = curry(function(iterator, list) {
      return _.groupBy(list, iterator);
    });
    invoke = curry(function(iterator, list) {
      return _.invoke(list, iterator);
    });
    indexOf = curry(function(value, list) {
      return _.indexOf(list, value);
    });
    sort = function(list) {
      return list.concat().sort();
    };
    reduce = curry(function(iterator, memo, list) {
      return _.reduce(list, iterator, memo);
    });
    head = first = _.first;
    last = _.last;
    tail = rest = _.rest;
    us = {
      find: find,
      map: map,
      filter: filter,
      reduce: reduce,
      memoize: memoize,
      compose: compose,
      min: min,
      max: max,
      each: each,
      head: head,
      first: first,
      last: last,
      tail: tail,
      rest: rest,
      sortBy: sortBy,
      groupBy: groupBy,
      invoke: invoke,
      indexOf: indexOf,
      sort: sort
    };
    reverse = function(arr) {
      return arr.concat().reverse();
    };
    take = curry(function(n, arr) {
      return first(arr, n);
    });
    arrays = {
      reverse: reverse,
      take: take
    };
    return _.extend(functions, objects, basics, us, arrays, debug);
  };

  if ((typeof define !== "undefined" && define !== null ? define.amd : void 0) != null) {
    define(['underscore'], function(_) {
      return fjs(_);
    });
  } else if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    _ = require('underscore');
    module.exports = fjs(_);
  }

}).call(this);
